In [5]:
import numpy as np
import matplotlib.pyplot as plt
import scipy.linalg as la
%matplotlib inline

# scipy.linalg.eig
The function scipy.linalg.eig computes eigenvalues and eigenvectors of a square matrix .

Let's consider a simple example with a diagonal matrix:

In [6]:
A = np.array([[1,0],[0,-2]])
print(A)

[[ 1  0]
 [ 0 -2]]


The function la.eig returns a tuple (eigvals,eigvecs) where eigvals is a 1D NumPy array of complex numbers giving the eigenvalues of A , and eigvecs is a 2D NumPy array with the corresponding eigenvectors in the columns:

In [7]:
results = la.eig(A)

In [9]:
results

(array([ 1.+0.j, -2.+0.j]), array([[1., 0.],
        [0., 1.]]))

In [8]:
print(results[0])

[ 1.+0.j -2.+0.j]


The corresponding eigenvectors are:

In [10]:
print(results[1])

[[1. 0.]
 [0. 1.]]


We can unpack the tuple:

In [11]:
eigvals, eigvecs = la.eig(A)
print(eigvals)

[ 1.+0.j -2.+0.j]


In [12]:
print(eigvecs)


[[1. 0.]
 [0. 1.]]


If we know that the eigenvalues are real numbers (ie. if A is symmetric), then we can use the NumPy array method .real to convert the array of eigenvalues to real numbers:

In [13]:
eigvals = eigvals.real
print(eigvals)

[ 1. -2.]


Notice that the position of an eigenvalue in the array eigvals correspond to the column in eigvecs with its eigenvector:

In [14]:
lambda1 = eigvals[1]
print(lambda1)

-2.0


In [15]:
v1 = eigvecs[:,1].reshape(2,1)
print(v1)

[[0.]
 [1.]]


In [16]:
A @ v1

array([[ 0.],
       [-2.]])

In [17]:
lambda1 * v1

array([[-0.],
       [-2.]])

# Symmetric Matrices
The eigenvalues of a symmetric matrix are always real and the eigenvectors are always orthogonal! Let's verify these facts with some random matrices:

In [18]:
n = 4
P = np.random.randint(0,10,(n,n))
print(P)

[[7 1 8 9]
 [2 7 4 7]
 [2 1 8 7]
 [9 5 5 2]]


Create the symmetric matrix S = P + Transpose of P

In [19]:
S = P @ P.T
print(S)

[[195 116 142 126]
 [116 118  92  87]
 [142  92 118  77]
 [126  87  77 135]]


In [20]:
evals, evecs = la.eig(S)
print(evals)

[472.02125452+0.j   4.24192708+0.j  35.76914959+0.j  53.96766881+0.j]


The eigenvalues all have zero imaginary part and so they are indeed real numbers:

The corresponding eigenvectors of  are:

In [21]:
print(evecs)

[[-0.62547295 -0.62066236 -0.42979219 -0.19707994]
 [-0.43627818 -0.1618911   0.88446087 -0.03437421]
 [-0.46260145  0.71157218 -0.11797676 -0.51550598]
 [-0.45215577  0.28676565 -0.13816338  0.83320556]]


Let's check that the eigenvectors are orthogonal to each other:

In [22]:
v1 = evecs[:,0] # First column is the first eigenvector
print(v1)

[-0.62547295 -0.43627818 -0.46260145 -0.45215577]


In [23]:
v2 = evecs[:,1] # Second column is the second eigenvector
print(v2)

[-0.62066236 -0.1618911   0.71157218  0.28676565]


In [24]:
v1 @ v2

3.3306690738754696e-16

The dot product of eigenvectors V1 and V2  is zero (the number above is very close to zero and is due to rounding errors in the computations) and so they are orthogonal!

In [26]:
import numpy as np
m = np.matrix([[2, -1, 0],
               [-1, 2, -1],
               [0, -1, 2]])

eigenvalues = np.linalg.eigvals(m)
print (eigenvalues)

[3.41421356 2.         0.58578644]


# Compute the eigenvalues and eigenvectors of a Hermitian or symmetric matrix

In [27]:
import numpy as np
m = np.matrix([[2, -1, 0],
               [-1, 2, -1],
               [0, -1, 2]])
eigenvalues, eigenvectors = np.linalg.eigh(m)
print (eigenvalues)

[0.58578644 2.         3.41421356]


# Compute the QR factorization of a matrix 

In [28]:
import numpy as np
m = np.matrix([[2, -1],
               [-1, 2],
               [0, -1]])

orthonormal, upper_triangle = np.linalg.qr(m, mode="raw")
print (orthonormal)

[[-2.23606798 -0.23606798  0.        ]
 [ 1.78885438 -1.67332005 -0.33167927]]
